apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-postgres-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: files-postgres-volume